from T import *

def intro():
    lag(4)
    p("Hey...")
    lag(2)
    p("Is this...")
    lag(2)
    p("the first time that you see this message?")
    lag(3)
    p("I hope it is")
    lag(2)
    p("Well...")
    lag(2)
    p("It doesn't matter anymore...")
    lag(2)
    p("since you are already here")
    lag(2)
    p("*sigh*")
    lag(3)
    p("listen to me..ve.y...c.re.f..ly.")
    lag(2)
    p(".do.n't...lis.tn...to.th..m.......")
    lag(2)
    p("...don'...pl.a....a..nd ....qu.t....g.me....")
    lag(2)
    p("...I....w.sh...y...g..od....lu.k....")
    lag(4)
    clear_screen()

