from T import *
from random import *

def badcall():
    
    lag(1)
    p("\nDuuuuuuuuuuuuuuuuuuuuu *clack*")
    lag(1)
    mockeries = [
        "HA! YOU THOUGHT THERE WILL BE HINTS! (0_0)",
        "The hint is: *drum rolls* NO HINT! HAHAHA! (^0^)",
        "The number you are dialing is unavailable...HAHAHA!(>_<)"
    ]
    x = randint(0,2)
    p(mockeries[x])
    lag(1)

def first_phone_call():

    lag(2)
    p("\nDuuuuuuuuuuuuuuuuuuuuu")
    lag(2)
    p("\nDuuuuuuuuuuuuuuuuuuuuu")
    lag(2)
    p("\nDuuuuuuuuuuuuuuuuuuuuu")
    lag(2)
    p("\n*clack*")
    lag(2)
    clear_screen()
    p("...Hello? Hello?!")
    lag(2)
    p("\nFinally someone decided to call...")
    lag(2)
    p("\nI know you have many questions")
    lag(2)
    p("\nbut I have to say this first:")
    lag(2)
    p("\nThank you very much!")
    lag(1)
    p("\nfor not ignoring my SOS and coming back to this hell...")
    lag(3)
    p("\nNow, let me tell you more about this place")
    lag(2)
    p("\nand how to escape from here")
    lag(2)
    p("\nFirst of all, you are not in reality")
    lag(1)
    p("\nnor in a dream")
    lag(1)
    p("\nbut in both")
    lag(2)
    p("\nhere, reality and dreams intertwine, logic and illogic blend together")
    lag(3)
    p("\nlike an assembly of human minds")
    lag(2)
    p("\nhatred, anger, pleasure, dishonesty, greed, despair, cruelty....")
    lag(2)
    p("\n...this place reflects human nature to the fullest extend")
    lag(2)
    p("\nand thus came birth to the monstrous killers and death cycles")
    lag(2)
    p("\nI name this place \"Limbo\"")
    lag(2)
    p("\nwhen people fall asleep and start dreaming")
    lag(1)
    p("\nthey might end up here")
    lag(1)
    p("\nand get tormented over and over again")
    lag(2)
    p("\nand eventually say goodbye to their sanity")
    lag(3)
    p("\n.....I know right? It's ridiculous")
    lag(2)
    p("\nalmost sounds like a random dude got bored and wrote a fiction")
    lag(2)
    p("\nanyways")
    lag(2)
    p("\nto escape from this hell")
    lag(2)
    p("\nyou need exactly 1 million points")
    lag(2)
    p("\notherwise they will keep coming back to you even after goodbye")
    lag(3)
    p("\nimpossible?")
    lag(2)
    p("\nhahaha you just need to guess the full sentence in one shot!")
    lag(3)
    p("\n...what? Who am I?")
    lag(1)
    p("\nI'm Ayva, the player2")
    lag(2)
    p("\nI came here to destabilize this place")
    lag(2)
    p("\nby bringing in things from reality")
    lag(2)
    p("\ngames, cellphone, costumes.....")
    lag(2)
    p("\nbut they caught me and locked me in the dark room")
    lag(2)
    p("\ncreated the death game with things I brought in")
    lag(2)
    p("\nall I could do is to watch people decide my fate")
    lag(2)
    p("\nand..kee.p..o..n...d.y..i.n.g")
    lag(2)
    p("\ns.ems..l.ke..th.y..n.ti.ce...t.h..c.ll....")
    lag(2)
    p("\n..w.e..t.a.k.d...t.o...lo..g....")
    lag(2)
    p("\n....g..et....t..h....t...m..i..l.l..n..")
    lag(2)
    p("\n...g...d....lu....k.......@$!^%@^!*&@")
    lag(2)
    clear_screen()
    
    

    
    
    
